#!/usr/bin/env python3
"""
Setup Google Drive folder structure for Studex agents.
Agents can read/write to these folders.
"""

import json
import os
from google.auth.transport.requests import Request
from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

# Service account credentials
SERVICE_ACCOUNT_FILE = os.path.expanduser("~/studex-agent-drive-key.json")
SERVICE_ACCOUNT_EMAIL = "studex-agent-drive@social-engine-493019.iam.gserviceaccount.com"

# Scopes
SCOPES = ["https://www.googleapis.com/auth/drive"]

def setup_drive():
    """Set up Google Drive folders for Studex agents."""

    # Authenticate
    creds = Credentials.from_service_account_file(SERVICE_ACCOUNT_FILE, scopes=SCOPES)
    drive_service = build("drive", "v3", credentials=creds)

    print("🚀 Setting up Google Drive for Studex Agents...\n")

    # Create root Studex folder
    root_folder_metadata = {
        "name": "Studex",
        "mimeType": "application/vnd.google-apps.folder",
        "description": "Root folder for Studex operations"
    }
    root_folder = drive_service.files().create(body=root_folder_metadata, fields="id").execute()
    root_id = root_folder.get("id")
    print(f"✅ Created root folder: Studex")
    print(f"   ID: {root_id}\n")

    # Create subfolders
    subfolders = {
        "Meat": "Studex Meat business (products, orders, inventory)",
        "Content": "Content assets (designs, videos, images)",
        "Agents": "Agent logs, decisions, outputs",
        "Analytics": "Sales data, engagement metrics, reports",
        "Config": "Configuration files, settings"
    }

    folder_ids = {"root": root_id}

    for folder_name, description in subfolders.items():
        folder_metadata = {
            "name": folder_name,
            "mimeType": "application/vnd.google-apps.folder",
            "parents": [root_id],
            "description": description
        }
        folder = drive_service.files().create(body=folder_metadata, fields="id").execute()
        folder_ids[folder_name.lower()] = folder.get("id")
        print(f"✅ Created folder: {folder_name}")
        print(f"   ID: {folder_ids[folder_name.lower()]}")

    print(f"\n🔐 Sharing root folder with service account...")

    # Share root folder with service account
    permission = {
        "type": "user",
        "role": "editor",
        "emailAddress": SERVICE_ACCOUNT_EMAIL
    }
    drive_service.permissions().create(
        fileId=root_id,
        body=permission,
        fields="id"
    ).execute()
    print(f"✅ Shared with: {SERVICE_ACCOUNT_EMAIL}\n")

    # Output configuration
    config = {
        "GOOGLE_DRIVE_STUDEX_FOLDER_ID": root_id,
        "GOOGLE_DRIVE_SUBFOLDERS": folder_ids
    }

    print("📋 Add to .env:\n")
    print(f'GOOGLE_DRIVE_STUDEX_FOLDER_ID={root_id}')
    print(f'\nSubfolder IDs (for reference):')
    for name, id in folder_ids.items():
        print(f'  GOOGLE_DRIVE_{name.upper()}_FOLDER_ID={id}')

    # Save to file
    with open(".env.drive", "w") as f:
        f.write(f"# Google Drive Configuration (generated by setup-google-drive.py)\n")
        f.write(f"GOOGLE_DRIVE_STUDEX_FOLDER_ID={root_id}\n")
        for name, id in folder_ids.items():
            if name != "root":
                f.write(f"GOOGLE_DRIVE_{name.upper()}_FOLDER_ID={id}\n")

    print(f"\n✅ Config saved to: .env.drive")
    print(f"   Merge into .env manually\n")

    return folder_ids

if __name__ == "__main__":
    try:
        setup_drive()
    except Exception as e:
        print(f"❌ Error: {e}")
        print("\nMake sure:")
        print("  1. ~/studex-agent-drive-key.json exists")
        print("  2. Google Drive API is enabled in Google Cloud")
        print("  3. Service account has permissions")
